### ISSUE TITLE
AttributeError: 'DiscordAccount' object has no attribute 'username'

### ISSUE THREAD

**Issue by Name277** [Alkosik/Discord-Alt-Token-Generator#1]
This error occurs sometimes but not always when the script is attempting to create an account, this error doesn't fill in the Username box and then crashes.

Here is the full error on cmd (Using Windows 10):
https://pastebin.com/fvVEbqvj

I used the following settings:
[amount of tokens: 2] [my windows name] [register delay: 30] [save usedata: false] [tokens file name: tokens] [invite to server: empty] [channel url: empty]

Chrome version: 87
Chromium Driver version: 87.0.4280.88

**Comment by Alkosik** [comment]
I fixed the issue. Re-download the scripts and try again.
